DGCrafts/Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DGCrafts.Models
{
    public class Item
    {
        public int ItemID { get; set; }

        public string ItemName { get; set; }

        public string ItemDescription { get; set; }

        public double UnitPrice { get; set; }

        public int AmtAvailable { get; set; }

        
    }
}

DGCrafts/Components/ImageRetrieverViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DGCrafts.Repository;


namespace DGCrafts.Components
{
    public class ImageRetrieverViewComponent : ViewComponent
    {
        private ICraftRepository repository;

        public ImageRetrieverViewComponent(ICraftRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke(int itemId)
        {
            return View(repository.GetImage(itemId));
        }
    }
}

DGCrafts/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DGCrafts.Repository;
using DGCrafts.Models;
using DGCrafts.Models.ViewModels;

namespace DGCrafts.Controllers
{
    public class CartController : Controller
    {
        private ICraftRepository repository;
        private Cart _Cart { get; set; }
        

        public CartController(ICraftRepository repo, Cart cartservice)
        {
            repository = repo;
            _Cart = cartservice;

            
        }

        public IActionResult Index(string returnUrl)
        { 
            return View(new CartIndexViewModel
            { 
                Cart = _Cart,
                ReturnUrl = returnUrl
            });
        }




        public RedirectToActionResult AddToCart(int itemId, int quantity, string returnUrl)// How do you know how much the Customer has order with Amt Available?
        {
            Item item = repository.GetItems()
                .FirstOrDefault(p => p.ItemID == itemId);
            if (item != null)
            {
                _Cart.AddItem(item, quantity);
                var newAmt = repository.GetItem(item.ItemID).AmtAvailable - quantity;

                Item updateItem = new Item
                {
                    ItemID = item.ItemID,
                    ItemDescription = item.ItemDescription,
                    ItemName = item.ItemName,
                    AmtAvailable = newAmt,
                    UnitPrice = item.UnitPrice
                };

                repository.SaveItem(updateItem);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        //public RedirectToActionResult AddToCart(Item cItem, string returnUrl)
        //{
        //    Item item = repository.GetItems()
        //        .FirstOrDefault(p => p.ItemID == cItem.ItemID);
        //    if (item != null)
        //    {
        //        _Cart.AddItem(cItem, cItem.AmtAvailable);
        //    }

        //    return RedirectToAction("Index", new { returnUrl });
        //}

        
        public RedirectToActionResult Remove(int itemId, int quantity, string returnUrl)
        {
            Item item = repository.GetItems()
               .FirstOrDefault(p => p.ItemID == itemId);
            if (item != null)
            {
                _Cart.RemoveLine(item);
                var newAmt = repository.GetItem(item.ItemID).AmtAvailable + quantity;

                Item updateItem = new Item
                {
                    ItemID = item.ItemID,
                    ItemDescription = item.ItemDescription,
                    ItemName = item.ItemName,
                    AmtAvailable = newAmt,
                    UnitPrice = item.UnitPrice
                };

                repository.SaveItem(updateItem);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

DGCrafts/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DGCrafts.Models;
using DGCrafts.Repository;

namespace DGCrafts.Controllers
{
    public class HomeController : Controller
    {
        private ICraftRepository repository;

        public HomeController(ICraftRepository repo)
        {
            repository = repo;
        }

        public IActionResult Index()
        {
            var model = repository.GetItems();
            return View(model);
        }

        public IActionResult Item(int itemId)
        {
            var model = repository.GetItem(itemId);
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

       
    }
}

DGCrafts/Views/Home/Index.cshtml
@model IEnumerable<Item>

@{
    ViewData["Title"] = "Welcome!";

    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

<h3>Welcome Customer!</h3>



<div id="announcements" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#announcements" data-slide-to="0" class="active"></li>
        <li data-target="#announcements" data-slide-to="1"></li>
        <li data-target="#announcements" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="card mb-3" style="max-width: 1500px;">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="~/Images/default-image.jpg" class="card-img" alt="AP1" />
                    </div>
                    <div class="col-md-8 bg-secondary">
                        <div class="card-body">
                            <h5 class="card-title">Announcement 1</h5>
                            <p class="card-text">Words words words for the Announcements</p>
                            <p class="card-text"><small class="text-light">Sale ends: Sept 20, 2020</small></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="card mb-3" style="max-width: 1500px;">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="~/Images/default-image3.jpg" class="card-img" alt="AP2">
                    </div>
                    <div class="col-md-8 bg-secondary">
                        <div class="card-body">
                            <h5 class="card-title">Announcement 2</h5>
                            <p class="card-text">Words words words for the second announcement</p>
                            <p class="card-text"><small class="text-light">updated date</small></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="card mb-3" style="max-width: 1500px;">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="~/Images/default-image.jpg" class="card-img" alt="AP3">
                    </div>
                    <div class="col-md-8 bg-secondary">
                        <div class="card-body">
                            <h5 class="card-title">Announcement 3</h5>
                            <p class="card-text">Words words words for the third announcement</p>
                            <p class="card-text"><small class="text-light">updated date</small></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#announcements" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#announcements" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


@{ int row = (int)Math.Ceiling((double)(Model.Count() / 3.0));

    int counter = 0;}
@for (int i = 0; i < row; i++)
{
    <div class="row pb-4">
        @{
            var model = Model.Skip(counter).Take(3);
            foreach (var item in model)
            {
                <text>
                    <a asp-action="Item" asp-route-ItemId="@item.ItemID">
                        <div class="col-sm-3 mx-4">
                            <div class="card" style="width: 18rem;">
                                @await Component.InvokeAsync("ImageRetriever", new { itemId = item.ItemID })
                                <div class="card-body">
                                    <p class="card-text">@item.ItemName</p>
                                    <p class="card-text"><b>@item.UnitPrice.ToString("c")</b></p>
                                </div>
                            </div>
                        </div>
                    </a>
                </text>
            }
            counter += 3;
        }

    </div>
}

DGCrafts/Views/Home/Item.cshtml
@model DGCrafts.Models.Item
@{
    ViewData["Title"] = "Item to Buy";

    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}


    <div class="text-center">

        @await Component.InvokeAsync("ImageRetriever", new { itemId = Model.ItemID })

        @*<div id="itemCarousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">

                </div>
                <div class="carousel-item">
                    <img src="~/Images/default-image.jpg" />
                </div>
                <div class="carousel-item">
                    <img src="~/Images/default-image.jpg" />
                </div>
            </div>
            <a class="carousel-control-prev" href="#itemCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            </a>
            <a class="carousel-control-next" href="#itemCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
            </a>*@
        </div>


        <div class="text-left">
            <h4>@Model.ItemName</h4>

            <div>
                <b>@Model.UnitPrice.ToString("c")</b>
            </div>

            <div>
                <p>@Model.ItemDescription</p>
            </div>

            <div>
                <form asp-controller="Cart" asp-action="AddToCart">
                    <select  name="quantity">
                        @for (int i = 1; i <= Model.AmtAvailable; i++)
                        {
                            <option value="@i">@i</option>
                        }
                    </select>
                    <div class="text-right">
                        <input type="hidden" asp-for="@Model.ItemID" />
                        <input class="btn btn-dark" value="Add to Cart" type="submit" />


                    </div>
                </form>



            </div>

        </div>


    </div>
 

       