DGCrafts/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace DGCrafts.Models
{
    public class Cart
    {


        public List<CartLine> Lines { get; set; } = new List<CartLine>();
        public virtual void AddItem(Item item, int quantity)
        {
            CartLine line = Lines
                .Where(i => i.Item.ItemID == item.ItemID)
                .FirstOrDefault();
            if (line == null)
            {
                Lines.Add(new CartLine
                {
                    Item = item,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }

        public virtual void RemoveLine(Item item) =>
            Lines.RemoveAll(p => p.Item.ItemID == item.ItemID);

        public decimal ComputeTotalValue() 
        {
           return (decimal)Lines.Sum(s => s.Item.UnitPrice * s.Quantity);
        }

        public virtual void Clear() => Lines.Clear();

    }

    public class CartLine
    {
        public int CartLineID { get; set; }
        public Item Item { get; set; }
        public int Quantity { get; set; }
    }
}
    

DGCrafts/Components/ImageRetrieverViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DGCrafts.Repository;


namespace DGCrafts.Components
{
    public class ImageRetrieverViewComponent : ViewComponent
    {
        private ICraftRepository repository;

        public ImageRetrieverViewComponent(ICraftRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke(int itemId)
        {
            return View(repository.GetImage(itemId));
        }
    }
}

DGCrafts/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DGCrafts.Repository;
using DGCrafts.Models;
using DGCrafts.Models.ViewModels;

namespace DGCrafts.Controllers
{
    public class CartController : Controller
    {
        private ICraftRepository repository;
        private Cart _Cart { get; set; }
        

        public CartController(ICraftRepository repo, Cart cartservice)
        {
            repository = repo;
            _Cart = cartservice;

            
        }

        public IActionResult Index(string returnUrl)
        { 
            return View(new CartIndexViewModel
            { 
                Cart = _Cart,
                ReturnUrl = returnUrl
            });
        }




        public RedirectToActionResult AddToCart(int itemId, int quantity, string returnUrl)// How do you know how much the Customer has order with Amt Available?
        {
            Item item = repository.GetItems()
                .FirstOrDefault(p => p.ItemID == itemId);
            if (item != null)
            {
                _Cart.AddItem(item, quantity);
                var newAmt = repository.GetItem(item.ItemID).AmtAvailable - quantity;

                Item updateItem = new Item
                {
                    ItemID = item.ItemID,
                    ItemDescription = item.ItemDescription,
                    ItemName = item.ItemName,
                    AmtAvailable = newAmt,
                    UnitPrice = item.UnitPrice
                };

                repository.SaveItem(updateItem);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        //public RedirectToActionResult AddToCart(Item cItem, string returnUrl)
        //{
        //    Item item = repository.GetItems()
        //        .FirstOrDefault(p => p.ItemID == cItem.ItemID);
        //    if (item != null)
        //    {
        //        _Cart.AddItem(cItem, cItem.AmtAvailable);
        //    }

        //    return RedirectToAction("Index", new { returnUrl });
        //}

        
        public RedirectToActionResult Remove(int itemId, int quantity, string returnUrl)
        {
            Item item = repository.GetItems()
               .FirstOrDefault(p => p.ItemID == itemId);
            if (item != null)
            {
                _Cart.RemoveLine(item);
                var newAmt = repository.GetItem(item.ItemID).AmtAvailable + quantity;

                Item updateItem = new Item
                {
                    ItemID = item.ItemID,
                    ItemDescription = item.ItemDescription,
                    ItemName = item.ItemName,
                    AmtAvailable = newAmt,
                    UnitPrice = item.UnitPrice
                };

                repository.SaveItem(updateItem);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

DGCrafts/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DGCrafts.Models;
using DGCrafts.Repository;

namespace DGCrafts.Controllers
{
    public class OrderController : Controller
    {

        private IOrderRepository repository;
        private Cart cart;

        public OrderController(IOrderRepository repoService, Cart cartservice)
        {
            repository = repoService;
            cart = cartservice;
        }

        public ViewResult ShippingForm()
        {
            return View(new ShippingInfo());
        }

        [HttpPost]
        public IActionResult ShippingForm(ShippingInfo order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                cart.Clear();
                return RedirectToAction(nameof(Confirmation));
            }
            else
            {
                return View(order);
            }
        }



        public IActionResult Confirmation()
        {
            cart.Clear();
            return View();
        }
    }
}

DGCrafts/Views/Cart/Index.cshtml
@model CartIndexViewModel

@{ 
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

<h3>Customer Cart</h3>

<table>
    @* for (int i = 0; i < 5; i++)*@

    @{
        foreach (var line in Model.Cart.Lines)

        {
            <tr>
                <td>
                    <div class="card mb-4 mr-4" style="max-width: 350px;">
                        <div class="row no-gutters">
                            <div class="col-md-4 m-3">
                                @await Component.InvokeAsync("ImageRetriever", new { itemId = line.Item.ItemID })
                            </div>
                            <div class="col-md-5 bg-white">
                                <div class="card-body">
                                    <h5 class="card-title">@line.Item.ItemName</h5>
                                    <p class="card-text"><small class="text-dark"><b>@line.Item.UnitPrice.ToString("c")</b></small></p>
                                    <p class="card-text"><small class="text-success">@line.Quantity</small></p>
                                    <form asp-action="Remove">
                                        @*<select name="quantity">
                                            @for (int i = 1; i <= line.Item.AmtAvailable; i++)
                                            {
                                                @if (i == line.Quantity)
                                                {
                                                    <option selected="@i" value="@i">@i</option>
                                                }
                                                <option value="@i">@i</option>

                                            }

                                        </select>*@

                                        <input type="hidden" name="ItemID" value="@line.Item.ItemID" />
                                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                                        <input class="btn btn-dark" value="Remove" type="submit" />
                                    </form>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </td>
            </tr>
        }
    }

</table>
<div class="align-bottom">
    <div class="bg-dark ">
        <div class="text-md-right text-light mr-2">
            <h3>Total: @Model.Cart.ComputeTotalValue().ToString("c")</h3>
        </div>
    </div>
    <div class="row">

        <div class="float-lg-left">
            <a class="btn btn-outline-primary " asp-controller="Home" asp-action="Index"><span>Continue Shopping</span></a>
        </div>
        <div float="right">
        <a class="btn btn-outline-dark" asp-controller="Order" asp-action="ShippingForm"><span>Checkout</span></a>
        </div>
    </div>
   
    
</div>