DGCrafts/Models/Announcement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace DGCrafts.Models
{
    public class Announcement
    {
        [Key]
        public int ID { get; set; }

        public string Title { get; set; }

        public string AnnounceDescript { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }
    }
}

DGCrafts/Components/AnnouncementCardViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DGCrafts.Repository;
using Microsoft.AspNetCore.Mvc;

namespace DGCrafts.Components
{
    public class AnnouncementCardViewComponent : ViewComponent
    {
        private ICraftRepository repository;

        public AnnouncementCardViewComponent(ICraftRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            return View(repository.GetAnnouncements());
        }
    }
}

DGCrafts/Components/ImageRetrieverViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DGCrafts.Repository;


namespace DGCrafts.Components
{
    public class ImageRetrieverViewComponent : ViewComponent
    {
        private ICraftRepository repository;

        public ImageRetrieverViewComponent(ICraftRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke(int itemId)
        {
            return View(repository.GetImage(itemId));
        }
    }
}

DGCrafts/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DGCrafts.Models;
using DGCrafts.Repository;

namespace DGCrafts.Controllers
{
    public class OrderController : Controller
    {

        private IOrderRepository repository;
        private Cart cart;

        public OrderController(IOrderRepository repoService, Cart cartservice)
        {
            repository = repoService;
            cart = cartservice;
        }

        public ViewResult ShippingForm()
        {
            return View(new ShippingInfo());
        }

        [HttpPost]
        public IActionResult ShippingForm(ShippingInfo order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                cart.Clear();
                return RedirectToAction(nameof(Confirmation));
            }
            else
            {
                return View(order);
            }
        }



        public IActionResult Confirmation()
        {
            cart.Clear();
            return View();
        }
    }
}

DGCrafts/Views/Admin/Announcements.cshtml
@model IEnumerable<Announcement>
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

    <table>
        <tr>
            <th>TITLE</th>
            <th>Start Date</th>
            <th>End Date</th>
        </tr>
        @foreach (var announcement in Model)
        {
        <tr>
            <td>@announcement.Title</td>
            <td>@announcement.StartDate</td>
            <td>@announcement.EndDate</td>
            <td class="text-center">
                <form method="post">
                    <a asp-action="EditAnnouncement" class="btn btn-sm btn-warning"
                       asp-route-Id="@announcement.ID">
                        Edit
                    </a>
                    <input type="hidden" name="ItemID" value="@announcement.ID" />
                    <button type="submit"asp-route-Id="@announcement.ID" asp-action="RemoveAnnouncement" class="btn btn-danger btn-sm">
                        Delete
                    </button>
                </form>
            </td>

        </tr>
        }
    </table>

<a asp-action="MakeAnnouncement" class="btn btn-success">
    <span>Make New Announcement</span>
</a>

<a asp-action="Index" class="btn btn-danger">
    <span>Cancel</span>
</a>

DGCrafts/Views/Admin/Delete.cshtml
@model DGCrafts.Models.Item

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>@Model.ItemName</h4>
    <div class="text-center">
        @await Component.InvokeAsync("ImageRetriever", new { itemId = Model.ItemID })
    </div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AmtAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AmtAvailable)
        </dd>
    </dl>
    
    <form asp-action="DeleteItem">
        <input type="hidden" asp-for="ItemID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DGCrafts/Views/Admin/Edit.cshtml
@model DGCrafts.Models.Item

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ItemID" />
            <div class="form-group">
                <label asp-for="ItemName" class="control-label"></label>
                <input asp-for="ItemName" class="form-control" />
                <span asp-validation-for="ItemName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemDescription" class="control-label"></label>
                <input asp-for="ItemDescription" class="form-control" />
                <span asp-validation-for="ItemDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AmtAvailable" class="control-label"></label>
                <input asp-for="AmtAvailable" class="form-control" />
                <span asp-validation-for="AmtAvailable" class="text-danger"></span>
            </div>
            <div class="form-group">

                <input type="file" id="file1"
                       name="file1"
                       multiple="multiple" />



                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="EditStore">Back to List</a>

  </div>

DGCrafts/Views/Admin/EditStore.cshtml
@model IEnumerable<Item>

@{
    ViewData["Title"] = "Edit Store";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
    <h3>Edit Store</h3>

    <table>
       
        @foreach ( var item in Model)
        {
        <tr>
          
            <td>@item.ItemName</td>
            <td class="text-right">@item.UnitPrice.ToString("c")</td>
            <td class="text-center">
                <form  method="post">
                    <a asp-action="Edit" class="btn btn-sm btn-warning"
                       asp-route-ItemId="@item.ItemID">
                        Edit
                    </a>
                    <input type="hidden" name="ItemID" value="@item.ItemID" />
                    <button type="submit"asp-action="Delete" class="btn btn-danger btn-sm">
                        Delete
                    </button>
                </form>
            </td>
        </tr>
        }

    </table>

    <a asp-action="Create" class="btn btn-outline-success" >
       <span>Add New Items</span>
    </a>

    <a asp-action="Index" class="btn btn-outline-danger">
        <span>Cancel</span>
    </a>
    

DGCrafts/Views/Admin/Files.cshtml
@model Item
@{  Layout = "~/Views/Shared/_AdminLayout.cshtml";}

<h4>File Upload for Item</h4>

<form asp-action="Files" method="post" enctype="multipart/form-data">
    <input type="hidden" asp-for="ItemID"/>
    <div class="form-group">

        <input type="file" id="file1"
               name="file1"
               multiple="multiple" />

        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

DGCrafts/Views/Admin/Index.cshtml
@model IEnumerable<Item>


@{
    ViewData["Title"] = "Welcome Shop Owner";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

}

<h3>Welcome Shop Owner</h3>

<div id="announcements" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#announcements" data-slide-to="0" class="active"></li>
        <li data-target="#announcements" data-slide-to="1"></li>
        <li data-target="#announcements" data-slide-to="2"></li>
    </ol>
  
    <div class="carousel-inner">
        @for (int i = 0; i < 3; i++)
        {
                if (i == 0)
                {
                    <div class="carousel-item active">
                         @await Component.InvokeAsync("AnnouncementCard")
                    </div>
                }

                else
                {
                    <div class="carousel-item ">
                        @await Component.InvokeAsync("AnnouncementCard")
                    </div>
                }
         }
    </div>
    

    @*<div class="carousel-item active">
            <div class="card mb-3" style="max-width: 1500px;">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="~/Images/default-image.jpg" class="card-img" alt="AP1" />
                    </div>
                    <div class="col-md-8 bg-secondary">
                        <div class="card-body">
                            <h5 class="card-title">Announcement 1</h5>
                            <p class="card-text">Words words words for the Announcements</p>
                            <p class="card-text"><small class="text-light">Sale ends: Sept 20, 2020</small></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>*@

    <a class="carousel-control-prev" href="#announcements" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#announcements" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


@{  int row = (int)Math.Ceiling((double)(Model.Count() / 3.0));
    
    int counter = 0;}
@for (int i = 0; i < row; i++)
{
    <div class="row pb-4">
        @{
            var model = Model.Skip(counter).Take(3);
            foreach(var item in model)
            {
                <text>
                        <div class="col-sm-3 mx-4" >
                             <div class="card" style="width: 18rem;">
                                                
                                 @await Component.InvokeAsync("ImageRetriever", new { itemId = item.ItemID })
                                 <div class="card-body">
                                     <p class="card-text">@item.ItemName</p>
                                     <p class="card-text"><b>@item.UnitPrice.ToString("c")</b></p>
                                 </div>
                             </div>
                        </div>
                </text>
            }
            counter += 3;
         }
        
    </div>
}



<div class="row align-content-center">
    <a asp-action="Announcements" class="btn-lg btn-outline-dark">
            <span>Edit / Make Annoucements</span>
    </a>

    <a asp-action="EditStore" class="btn-lg btn-outline-dark">
            <span>Edit Store</span>
    </a>

    <a asp-action="Orders" class="btn-lg btn-outline-dark">
    <span>Orders</span>
    </a>

</div>

DGCrafts/Views/Admin/MakeAnnouncement.cshtml
@model DGCrafts.Models.Announcement
@{
    ViewData["Title"] = "Announcement Editor";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Announcements Editor</h2>

<form method="post">
    <div class="form-group">
        <input type="hidden" asp-for="ID" />
        <label asp-for="Title"></label>
        <input asp-for="Title" type="text" />
    </div>


    <div class="form-group">
        <textarea asp-for="AnnounceDescript" rows="10" cols="50" placeholder="Write Announcement here..."></textarea>
    </div>


    <div class="form-group">
        <label asp-for="StartDate"></label>
        <input type="date" asp-for="StartDate" name="StartDate" />
    </div>

    <div class="form-group">
        <label asp-for="EndDate"></label>
        <input type="date" asp-for="EndDate" name="EndDate" />
    </div>



    <input type="submit" asp-action="MakeAnnouncement" value="Save" class="btn btn-outline-dark">
    <input type="submit" asp-action="Announcements" value="Cancel" class="btn btn-warning">
    <input type="submit" asp-route-Id="@Model.ID" asp-action="RemoveAnnouncement" value="Delete" class="btn btn-danger">

</form>

DGCrafts/Views/Admin/Orders.cshtml
@model IEnumerable<ShippingInfo>

@{   Layout = "~/Views/Shared/_AdminLayout.cshtml";}


<h3>Orders</h3>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Customer</th>
            <th>Crafts Ordered</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model)
        {
        <tr>
            <td>@order.CustomerName</td>
         </tr>
        }

    </tbody>
</table>

DGCrafts/Views/Admin/RemoveAnnouncement.cshtml
@model DGCrafts.Models.Announcement

@{
    ViewData["Title"] = "RemoveAnnouncement";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>RemoveAnnouncement</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Announcement</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnnounceDescript)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnnounceDescript)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
    
    <form asp-action="Remove">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <input asp-action="Announcements" type="submit" value="Cancel" class="btn btn-warning" />
    </form>
</div>